# .readthedocs.yaml

version: 2

# Configuración de Python
python:
  version: "3.8"  
  install:
    - requirements: doc-RobotsExploradores/source/requirements.txt

# Configuración de Sphinx
sphinx:
  configuration: doc-RobotsExploradores/source/conf.py

# Opciones de build
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  system_packages: true
  apt_packages:
    - graphviz
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - latexmk
    
# Formatos de salida
formats:
  - htmlzip
  - pdf
