# .readthedocs.yaml

version: 2

# Idioma y versión de Python
language: es
python:
  version: "3.8.10"  # Asegúrate de usar una versión compatible
  install:
    - requirements: doc-RobotsExploradores/source/requirements.txt

# Configuración específica de Sphinx
sphinx:
  configuration: doc-RobotsExploradores/source/conf.py

# Opciones de build
build:
  os: ubuntu-20.04  
  tools:
    sphinx: "5.3.0"  

# Formatos de salida
formats:
  - htmlzip
  - pdf  
