# Archivo config.yaml para TurtleBotObjectDetectionNode

# ************************************************
#        PARÁMETROS DE LA DETECCIÓN DE OBJETOS
# ************************************************

image_topic:            "camera/rgb/image_raw" #stage: "/image" 
processed_image_topic:  "processed_image"
depth_topic:            "camera/depth/image_raw" #stage: "/depth"
odometry_topic:         "odom"
camera_info_topic:      camera/depth/camera_info #stage: "/camera_info"
process_frequency:      10.0  # Frecuencia de procesamiento en Hz

#Offset para retranquear la posicin del objeto detectaod para evitar que la estacion se cree sobre el propio objeto y no se pueda planificar alli

offset_distancia_deteccion:                 0.50 #METROS


