# move_base_params.yaml

move_base:
  global_costmap:
    obstacle_layer:
      enabled: true
      max_obstacle_height: 0.6
      origin_z: 0.0
      z_resolution: 0.2
      z_voxels: 2
      unknown_threshold: 15
      mark_threshold: 0
      combination_method: 1
      track_unknown_space: false    # Modificado a true
      obstacle_range: 2.5
      raytrace_range: 3.0
      publish_voxel_map: false
      observation_sources: scan bump
      scan:
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        min_obstacle_height: 0.25
        max_obstacle_height: 0.35
      bump:
        data_type: PointCloud2
        topic: mobile_base/sensors/bumper_pointcloud
        marking: true
        clearing: false
        min_obstacle_height: 0.0
        max_obstacle_height: 0.15

    inflation_layer:
      enabled: true
      cost_scaling_factor: 5.0
      inflation_radius: 0.4

    static_layer:
      enabled: true

  local_costmap:
    obstacle_layer:
      enabled: true
      max_obstacle_height: 0.6
      origin_z: 0.0
      z_resolution: 0.2
      z_voxels: 2
      unknown_threshold: 15
      mark_threshold: 0
      combination_method: 1
      track_unknown_space: false    # Modificado a true
      obstacle_range: 2.5
      raytrace_range: 3.0
      publish_voxel_map: false
      observation_sources: scan bump
      scan:
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        min_obstacle_height: 0.25
        max_obstacle_height: 0.35
      bump:
        data_type: PointCloud2
        topic: mobile_base/sensors/bumper_pointcloud
        marking: true
        clearing: false
        min_obstacle_height: 0.0
        max_obstacle_height: 0.15

    inflation_layer:
      enabled: true
      cost_scaling_factor: 5.0
      inflation_radius: 0.4

    static_layer:
      enabled: true
